/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lhtw_openssl_OpensslUtils */

#ifndef _Included_com_lhtw_openssl_OpensslUtils
#define _Included_com_lhtw_openssl_OpensslUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    getPrivateKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lhtw_openssl_OpensslUtils_getPrivateKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    getPublicKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lhtw_openssl_OpensslUtils_getPublicKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    opensslGenrsa
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lhtw_openssl_OpensslUtils_opensslGenrsa
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    opensslReq
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lhtw_openssl_OpensslUtils_opensslReq
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    opensslCa
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_lhtw_openssl_OpensslUtils_opensslCa
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong, jstring, jint);

/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    opensslPkcs12
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lhtw_openssl_OpensslUtils_opensslPkcs12
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    createClientCertificateP12
 * Signature: (ILjava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lhtw_openssl_OpensslUtils_createClientCertificateP12
  (JNIEnv *, jobject, jint, jstring, jint, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     com_lhtw_openssl_OpensslUtils
 * Method:    createClientCertificateCrt
 * Signature: (ILjava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lhtw_openssl_OpensslUtils_createClientCertificateCrt
  (JNIEnv *, jobject, jint, jstring, jint, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
